project:
  type: website
  output-dir: docs

website:
  title: "meljanmor.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cv.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

