---
title: "Curriculum Vitae"
---

## **Professional Summary**

As a dedicated ecologist with a passion for exploring diverse aspects of ecology, I bring a wealth of knowledge and field experience to the table. My academic journey has led me to delve into various ecological topics, fostering a deep commitment to my work. Continuously evolving alongside the dynamic field of ecology, I am eager to contribute to its advancement while furthering my own learning. Proficient in grant and proposal writing, as well as adept in research methods and paper publication, I am well-equipped to tackle the challenges of ecological research. Whether in the laboratory or out in the field, my enthusiasm for studying ecology knows no bounds. I am looking forward to joining a team where I can continue growing while contributing to work that makes a meaningful impact.

## **Education**

**Colorado State University** (Fort Collins, Colorado U.S.)

Current M.S. student, Graduate Degree Program in Ecology

*Relevant coursework:* Foundations of Ecology, Ecosystem Ecology, Community Ecology, Advanced Topics in Ecology, Insect Ecology, Environmental Data Science Applications, & Design and Data Analysis for Researchers.


**Moravian College** (Bethlehem, Pennsylvania U.S.)

Degree: Bachelor of Science in Environmental Science (**May 202)**

*Relevant coursework:* Animal Behavior, Statistics, Environmental Policy, Environmental Chemistry, Marine Ecology, Climate Negotiations, Vertebrate Evolution Seminar, & Environmental Ethics.


**Northampton Community College** (East Stroudsburg, Pennsylvania U.S.)

*Major:* Environmental Science, **January 2018 - May 2019**

*Relevant coursework:* Ecology, Geographic Information Systems (GIS), Astronomy, Field Zoology, Environmental Biology, Environmental Sustainability, Physical Geology, Biology I, Biology II, Chemistry I, & Chemistry II.


## **Job Experience**

**Research Assistant, Lab Technician, and Field Technician** for Colorado State University (Fort Collins, CO)

*Research assistant/Spur IT Tech (June 2024  – June 2025)*

Edited and curated stories for the GMSO Impact(o) Map using ArcGIS StoryMaps. Supported CSU Spur’s IT Team by developing digital forms and implementing workflow automation through Power Automate, Power Pages, and Power Apps*.*

*Research assistant/Lab technician (August – December 2023)*

Responsible for specimen management, including placement, removal, and census of insect specimens pre- and post-intubation across successive generations in the Hufbauer lab. Managed a fungal outbreak within the lab environment. Prepared specialized mediums for insect populations, including those with pesticide additives. Maintained lab cleanliness and performed general upkeep duties.

*Research Assistant/Field Technician (May – June 2023)*

Lead a field crew from the University of Derby (U.K.) in Grand Teton (GRTE) and Yellowstone (YELL) National Park. Trained field crew in field safety, pollinators 101, standard operating procedures for scenarios such as heat stress, hiking and camping in bear country, lightning, etc. Surveyed sites and collected data on pollinators and floral resources via Epicollect5 (data gathering platform). Developed new sampling and testing procedures and methods (using plots, transects, and pollard walks). Created surveys on Epicollect5 and Survey123 (questions for each field site regarded land cover type, starting and ending weather conditions, plants in the field site, and pollinators found in the site). Performed data entry. Identified pollinators (of the Lepidoptera and Hymenoptera families) and floral resources found in each field site. Managed data. Installed, operated and maintained sampling equipment. Assisted in the development of the NPS permit that allowed us to operate this field season. Recommended resource management actions based on field observations.

*Research Assistant/Field Technician (May – August 2022)*

Similar field experience as my 2023 position. Lead a field crew from The Dijon Agro Institute (France) and the University of Derby in Grand Teton, Yellowstone, and Glacier (GLAC) National Park. Prepared, maintained, analyzed, and presented data for the University of Wyoming-National Park Service Research Station. Report was written regarding our findings at each field site in GRTE, YELL, and GLAC.

**Teaching Assistant (TA)** at Colorado State University(Fort Collins, CO)

*TA for Practicing Sustainability, ESS-440 (January – May 2024)*

Working with stakeholders (Colorado Natural Heritage Program) to allow students to use their skills in this capstone course. Communicate and organize weekly meetings, stakeholder events, and group projects for students (am currently managing three different groups for CNHP. Working with students to assist them in being more proficient in skills such as ArcGIS, Rstudio, CODEX, storymaps, filming, organization, and communication. Organized and participated in weekly meetings with professors, TAs, and stakeholders. Responsible for grading students on an array of assignments. Presented on various topics (resume building, working for the federal government, career paths in the field of environmental science, resources provided at CSU, etc.). Created assignments for students (description, rubric, assistive materials, etc.). Assisted professor in leading discussion sections. Assisted students in troubleshooting (ArcGIS, Rstudio, etc.), holding meetings with stakeholders, writing personal essays, building their resumes, and giving advice on graduate school.

*TA for Land Use Hydrology, WR-416 (August – December 2023)*

Provided support to students across various subjects, including what happens to water after rain or snow hits the ground surface and exploring how human activities alter the pathways of water. Graded all student assignments. Conducted weekly office hours for students.

*TA for Intro to GIS, NR-322 (January – May 2023)*

Facilitated a weekly GIS lab session, offering demonstrations and providing ongoing assistance to students during the sessions. Evaluated all student assignments and held weekly office hours to offer further support and guidance.

*TA for International Climate Negotiations, ESS-505 (August – December 2022)*

Coordinated student logistics for international travel to the Conference of the Parties (COP 27), ensuring their safety and well-being through weekly safety meetings with university staff. Held regular meetings with stakeholders from the Youth Environmental Alliance in Higher Education (YEAH) to discuss preparations and initiatives. Evaluated student assignments and provided weekly office hours for additional support. Collaborated with the YEAH network, Colorado State University (CSU), and the State Department to develop an interactive pavilion at COP27, serving as an artistic installation highlighting youth climate activism.


**Delaware Water Gap National Recreation Area (DEWA)** (Bushkill, Pennsylvania U.S.)

[Park Guide GS-04:]{.underline}

*May 2021 – November 2021 (Seasonal position / 38 - 46.5 hours per week)*

Fulfilled the same duties as my **Park Guide GS-03** position. Served as a uniformed front-line representative of the National Park Service. Roved the park both alone and with other employees throughout the park while in uniform, answering visitor inquiries and providing other information. Regularly communicated resource protection messages, such as leave no trace principles, to visitors. Interpreted the history and significance of Delaware Water Gap National Recreation Area (DEWA) through formal interpretive programs and informal visitor contacts, both onsite and offsite during community outreach events and educational programs.

Promoted the Junior Ranger program to young visitors Created and/or published content for DEWA’s NPS government website (e.g., Climate change page). Researched, developed, and created content for the park’s website and social media pages.

Created educational displays. Participated in the creation of the *Kids Guide to the Gap,* DEWA’s latest Junior Ranger activity. Helped write and interpret the park's cultural and natural resources. Created original activities for young visitors to actively and personally experience the park's cultural and natural resources. Created original digital artwork for the *Kids Guide to the Gap*.

Worked as a lead member of the pop-up team. Created visually appealing pop-up programs for visitors of all age groups in high and low-use areas of the park. Created fun activities for all ages for the pop-up programs.

Pop-up programs created:

-   Spotted lanternfly (SLF) pop-up: Program for all ages. Discussed what invasive species are with visitors. Taught visitors different ways to properly identify the different stages of SLF. Taught visitors how they can stop the spread of SLF. Taught visitors how this invasive species affects the ecosystem (e.g., trees, bees, humans). Taught visitors how to make a bird-friendly SLF trap at home. Answered visitor’s questions about SLF and other local invasive and native species.

-   Macroinvertebrate pop-up: Program for all ages. Discussed with visitors what macroinvertebrate means and defined what they are, why they are important to the environment, where they are found, and what each of them indicates. Caught live specimens and simulated their environment (leaf packs, different sized rocks, twigs) for visitors to see up close. Answered visitor’s questions about macroinvertebrates.

-   Pollinator pop-up: Program geared towards children. Discussed what pollination is with visitors. Highlighted different pollinators and what plants they are capable of pollinating. Discussed why pollinators are important with visitors of all age groups. Answered visitor’s questions about pollinators.

-   American shad pop-up: Program for all ages. Discussed the American shad with visitors and highlighted why they are important. Interpreted the park's history and the importance of undammed rivers. Discussed migration, the importance of watersheds, and the Leave No Trace Seven Principles (Center for Outdoor Ethics). Answered visitor’s questions about shad, the park's history, watersheds, and Leave No Trace.

*June 2020 – November 2020 (Seasonal position / 28 - 40 hours per week)*

Created activities for children in the park (ex: NPS bingo, NPS scavenger hunt, watercolor activity, rock paint activity, nature art activity, nature journal).

Led staff meetings that consisted of updating the interpretation department with new park information. Provided a safety tailgate for the interpretation department. Partook in adaptive management at the busiest locations of the park.

*May 2019 – September 2019 (Seasonal position / 24 - 32 hours per week)*

Fulfilled the same duties as my **Park Guide GS-03** position as well as: Maintained the status as the Lead Park Guide at Dingmans Falls Visitor Center. Provided guided tours for new volunteers.

Assisted Park Biologist with EcoCamp, a science-based summer program for middle school and high school students. Created and managed Pop-Up programs (topics varied from Macroinvertebrates, Pennsylvania stream ecology, Hidden World of Seeds, and survival techniques). Partook in DEWA training that explored creating amazing visitor experiences and telling stories that matter.

**Park Guide GS-03:**

*May 2017 – September 2017 (Seasonal / 24 - 32+ hrs. per week)*

*May 2018 – September 2018 (Seasonal / 24 - 32+ hrs. per week)*

Helped with guiding small groups and providing services to visitors. Related to visitors of varying interests and backgrounds. Utilized interpretive techniques (such as metaphors, storytelling, and analogies) suggested by others to facilitate intellectual and/or emotional connections between audiences' interests and their surroundings. Presented information to the public about the cultural, historical, and/or natural resources of interest of the park, area, facility, etc.

Oriented hikers to conditions and equipment needed to assure safety. Surveyed the local area to see what fauna and flora surround the park. Performed emergency duties to protect people, government property, and the park itself. Conducted Operational Risk Management Analysis, or GAR (green, amber, red) to determine risks and mitigate those risks.

\

**Adventure Sports** (Marshalls Creek, Pennsylvania U.S.)

[Base Staff:]{.underline}*May 2015 – September 2016 (Seasonal / 40 - 50+ hrs. per week)*

Completed a safety talk to each visitor we had before bringing them into the National Park for their river trip. Assisted over \~300 customers a day. Educated customers regarding rules, regulations, and safety concerns to gain compliance. Maintained knowledge of National Park Service rules and regulations. Interacted with others to resolve complaints and conflicts. Worked independently handling stressful or controversial situations. Stocked an information desk and displays with brochures. Assisted the public in planning visits to and recommending activities in the area.

Maintained knowledge of River Safety. Ensured superior customer experience by addressing customer concerns, demonstrating empathy, and resolving problems immediately. Provided a River Orientation for each customer so they felt safe and excited for their trip. Maintained information desk and replaced brochures and visitor packets when needed. Managed customer calls effectively and efficiently in a complex, fast-paced and challenging call center environment. Handled general maintenance and cleaning duties.

## **Achievements**

**Academic achievements:**

●       Dean’s List at Northampton Community College (Spring 2018, Fall 2018, Spring 2019, Fall 2019)

●       Dean’s List at Moravian College (Spring 2020, Fall 2021, Spring 2021)

●       Received the Founders Scholarship at Moravian College

●       Received the UW-NPS Small Grant for the *Sagebrush Blues* Project in GRTE, YELL, and GLAC

**Career achievements:**

●       National Park Service Performance-Based Cash Award from Delaware Water Gap National Recreation Area **(2020 and 2021)**

●       National Park Service Star (Special Thanks for Achievement) Award from Delaware Water Gap National Recreation Area **(2021)**

## **Trainings**

●      CITI Training (Research, Ethics, Compliance, and Safety Training) (2022)

●      IRB Training (Human participant research ethics training) (2022)

## **Publications and Presentations**

●       Lord JP, Moser RM, Buonocore EM, Sylvester EE, Morales MJ, Granitz AP, Disipio A, Blakely E, O’Sullivan-Evangelista SL, Mateo TF, Chlebove GJ, Carey CM, Lucas O. **2021**. Dominance Hierarchies in Marine Invertebrates. *The Biological Bulletin*.

●       Manz, M., Lord, J., & Morales, M. (2023). Ocean Acidification Impedes Foraging Behavior in the Mud Snail Ilyanassa obsoleta. Journal of Marine Science and Engineering, 11(3), 623.

●       Presented Independent Study, *Consequences of Ocean Acidification on Marine Snail Foraging Behavior*, at **Moravian College Scholars Day (2021)**

●       Presented *Climate Change in Delaware Water Gap National Recreation Area* (DEWA NRA) for the Interpretation division of **DEWA NRA** **(2021)**

●       Presented *The Power of Quality Education* at **Youth Environmental Alliance in Higher Education's 2020 Global Virtual Conference**

●       Youth Dialogues and the National Climate Assessment at the Conference of the Parties **(COP 27): Voices and Visions, The Art and Science of Climate Action (2022)**

●       Presented *The Sagebrush Blues: Butterfly Pollinator Assemblages in the GYE* at the **Greater Yellowstone Ecosystem Conference** **(2022)**

●       Presented *Voices and Visions, The Art and Science of Climate Action* at **CSU’s International Symposium (2023)**

●       Presented *How citizen science can help you* at the **Front Range Student Ecology Symposium** **(2023)**

## **Undergraduate Academic Experience**

●       **Youth Environmental Alliance in Higher Education:** August 2020 – May 2021

The Youth Environmental Alliance in Higher Education Network (YEAH) is grant funded through the National Science Foundation. This internship allowed me to interact with students from my teacher assistantship, Climate Negotiation course at Moravian College, and connect them to the YEAH network. The YEAH Network is working on a project that brings students together from several universities: Moravian College, Boston University, Michigan Tech University, Colorado College, Indiana University, Scripps Institution of Oceanography, University of Connecticut, University of Derby (UK), Vanderbilt University, La Molina University (Peru) and Monash University (Australia). Students were placed into teams that represent the United Nations Sustainable Development Goals (SDG’s). Each team had a fellow, and I was a fellow for SDG #4, which focuses on quality education. Each team did research into the SDG’s target goals to help create a case study. This fellowship allowed me to exercise my leadership and science communication skills. I learned about complex global environmental issues, climate advocacy, policies (local, federal, national), the United Nations, human rights, and gender issues through multicultural perspectives.

●       **Spring Cohort for Upper Darby Township:** January 2021 – May 2021

Through ICLEI- Local Governments for Sustainability, I helped Upper Darby township complete their greenhouse gas inventory and draft a Climate Action Plan (CAP) that incorporates a climate justice plan. Upper Darby is very diverse in its population and this experience has allowed me to further explore my interest in social equity as well as climate change. This experience required me to engage with stakeholders, the Mayor of Upper Darby, the Deputy Chief Administrative Officer, and the community (via online surveys) as part of the development of the climate action plan. Clearpath (emissions management software suite from ICLEI-USA) was used to review inventory and forecast emissions. Social justice, adaptation, mitigation, vulnerability assessments, and monitoring all played a major role in drafting the climate action plan. Adobe Photoshop and Canva were used to make infographics for community engagement.

●       Teaching assistant at Moravian College, Climate Negotiations on the International Stage (IDIS 298)

●       Assisted instructors (Drs. Diane Husic & Hilde Binford) with virtual students in this hybrid course.

●       Independent study in the Marine Biology lab at Moravian on mud snails and their ability to find food under acidified conditions.

●       Assisted in a class meta-analysis research project, which required individual proposals, group proposals, leading discussions, drafting scientific paper, and creating a group paper summary. The meta-analysis research project is published in The Biological Bulletin. 

●      Equipment used: Biltmore stick, calipers, chest waders, Clearpath, a digital probe, a field-scale, GIS, GPS, a hand magnifier, insect nets, life preservers, measuring tapes, meter sticks, microscopes, pruners, Secchi disks, soil pH tester, spectrophotometer, stopwatch, thermometer probe, a UV lamp, water level logger, and water pH tester.

## **Volunteer Work**

●      Volunteer for NPS DEWA Natural Resources

●          Dragonfly nymph collection (used to test mercury levels)

●          Crayfish collection (to determine the health of streams)

●          Collected both native and invasive species, seed collection for a wetland restoration project

●          Collected organisms for biotic index calculations

●          Took a seed collection training to learn about native species that were being collects, learned which seeds to collect, and learned different methods for seed collection and storage

●          Performed basic limnology tests (using Secci disk, recorded  temperature and dissolved oxygen at different depths)

●      Volunteer for NPS DEWA Cultural Resources

●      PennState Extension Master Watershed Steward

●          Tree planting, riparian buffer repairing, surveying watersheds, manual invasive species removal, water quality testing

●      Delaware Riverkeeper Network (fresh water mussel surveying) 

●      Delaware Highlands Conservancy Monitoring Volunteer

●      Owl Banding volunteer for Pocono Avian Research Center at Kettle Creek

●      Bioblitz volunteer, collected data on flora and fauna


## **Core Competencies**

●      Highly organized and keen on detail

●      Desire and ability to learn new skills

●      Experienced conducting fieldwork across diverse terrain and weather conditions

●      Demonstrates proficiency in collaborative teamwork and self-motivated to work independently

●      Robust technical writing, analytical, and communications skills for different audiences

## **Technical skills**

●       Research methods, research papers, and grant proposals

●       Rstudio (Machine Learning such as MaxEnt and Random Forest, statistical analysis, Markdown, Shiny, and Quarto)

●       ArcGIS (ArcToolbox, Spatial Analyst, ModelBuilder, ArcGIS Online, StoryMaps, Survey123)

●       GPS (Gaia, Garmin)

●       Microsoft Office Suite (Excel, Word, PowerPoint, Outlook, Teams, OneDrive) and Google drive suite

●       Google Suite (Drive, Docs, Sheets, Slides, Calendar, Forms, Meet)

●       Website Management (Content Management System \[CMS\] and WordPress)

●       Design (Canva, Adobe Photoshop, Photopea)

●       Social Media (Facebook, Twitter, Youtube, Instagram)


